# .streamlit/secrets.toml
WATSONX_API_KEY = P1b4IDAZcq9xUrH-YfnyLB9QSBFTFRRPK_W8IlqhY-0K
WATSONX_PROJECT_ID = 4514a1ea-f493-494f-8ab3-f9be973e4df6
WATSONX_URL = https://au-syd.ml.cloud.ibm.com
WATSONX_MODEL_ID=ibm/granite-3-3-8b-instruct
